//Find size of Variable
#include<iostream>
Using namespace std;
int main()
{
Cout<<"Size of char:"<<size of (char)<<"byte"<<endl;
Cout<<"size of int:"<<size of (int)<<"bytes"<<endl;
Cout<<"size of float:"<<size of (float)<<"bytes"<<endl;
Cout<<"size of double:"<<size of (double)<<"bytes"<<endl;
Return 0;
}

//Find product of two numbers
#include<iostream>
Using namespace std;
int main ()
{
//C+ program find product of two numbers
int X,Y,Product;
Product=3.4*5.5;
X=3.4;
Y=5.5;
//Product=X*Y;
Cout<<Product of two numbers is"<<Product;
Return 0;
}
